services:
  neo4j:
    image: neo4j:5.15-community
    container_name: book-reader-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - book-reader-network

  redis:
    image: redis:7-alpine
    container_name: book-reader-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - book-reader-network
    command: redis-server --appendonly yes

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  redis_data:

networks:
  book-reader-network:
    driver: bridge
